version: "3"

services:
  subtitle_api:
    container_name: subtitle_api
    image: hqwuzhaoyi/gpt-subtitle-api:latest
    restart: always
    volumes:
      - /Users/admin/workspace/gpt-subtitle/uploads:/app/uploads
    ports:
      - 3001:3001
    networks:
      - subtitle_app_network
    env_file:
      - .env
    depends_on:
      - subtitle_mysql
      - subtitle_redis

  subtitle_web:
    container_name: subtitle_web
    image: hqwuzhaoyi/gpt-subtitle-web:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - subtitle_app_network
    env_file:
      - .env

  subtitle_mysql:
    container_name: subtitle_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - subtitle_mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - subtitle_app_network

  subtitle_redis:
    container_name: subtitle_redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - subtitle_app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  subtitle_app_network:

# Volume for MySQL
volumes:
  subtitle_mysql_data:
