version: "3"

services:
  subtitle_api:
    container_name: subtitle_api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    volumes:
      - /Users/wuzhaoyi/workspace/gpt-subtitle/uploads:/app/uploads
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - subtitle_app_network
    env_file:
      - .env
    depends_on:
      - subtitle_mysql
      - subtitle_redis

  subtitle_web:
    container_name: subtitle_web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - WEB_PORT=3000
        - SERVER_PORT=3001
        - NEXT_PUBLIC_API_URL=http://localhost:3001
    restart: always
    ports:
      - ${WEB_PORT}:3000
    networks:
      - subtitle_app_network
    env_file:
      - .env
    depends_on:
      - subtitle_api

  subtitle_mysql:
    container_name: subtitle_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - subtitle_mysql_data:/var/lib/mysql
    networks:
      - subtitle_app_network
    ports:
      - ${MYSQL_PORT}:3306

  subtitle_redis:
    container_name: subtitle_redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - subtitle_app_network

networks:
  subtitle_app_network:

volumes:
  subtitle_mysql_data:
